#### 目录介绍
- 01.finally处理作用
- 02.finally执行分析
    - 2.1 finally一定会执行吗
    - 2.2 验证finally执行
- 03.finally和return
    - 3.1 finally和return案例1
    - 3.2 finally和return案例2
    - 3.5 try块里的return一定执行吗




### 01.finally处理作用
- 对于一些代码，可能希望无论是否抛出异常，这些代码都必须要执行。
    - 这通常包括内存回收之外的一些操作，因为内存回收是由垃圾回收器完成。为了达到这个效果，可以在catch块之后加上finally块。在finally块中处理这些代码。完整的异常处理如下：
    ```
    try{
    	//---
    }catch(Exception e1){
    	//---
    }catch(Exception e2){
    	//---
    }finally{
    	//---
    }
    ```
- 下面的示例用来证明finally字句不管异常是否抛出都能被执行：
    ```
    public class FinallyWorks {
    	static int count = 0;
    	public static void main(String[] args) {
    		while(true){
    			try{
    				if(count++ == 0){
    					throw new Exception();
    				}
    				System.out.println("No Exception");
				}catch(Exception e){
					System.out.println("Exception");
				}finally{
					System.out.println("In finally clause");
					if(count == 2){
						break;
					}
				}
			}
		}
	}
    ```
- 可以看到不管异常是否被抛出，finally字句都执行了。
    - 这个程序告诉我们，当程序发生了异常之后不能正确的回到原来的执行顺序上，我们可以在finally块中处理一些必要做的事情。
    - 比如打开文件的操作，当文件操作发生异常的时候，我们要确保文件被正确的关闭。





### 02.finally执行分析
#### 2.1 finally一定会执行吗
- finally是异常处理的统一出口，常用来实现资源释放，比如关闭文件，关于数据库连接等。不一定会被执行的。
- **在以下4种特殊情况下，finally块不会被执行：**
    - 1.在finally语句块中发生了异常。
    - 2.在前面的代码中用了System.exit()退出程序。
    - 3.程序所在的线程死亡。
    - 4.关闭CPU。



#### 2.2 验证finally执行
- **至少有两种情况下finally语句是不会被执行的：**
    - **try语句没有被执行到，如在try语句之前就返回了，这样finally语句就不会执行，这也说明了finally语句被执行的必要而非充分条件是：相应的try语句一定被执行到。**
    - **在try块中有`System.exit(0);`这样的语句，`System.exit(0);`是终止Java虚拟机JVM的，连JVM都停止了，所有都结束了，当然finally语句也不会被执行到。**



### 03.finally和return
- 探讨finally语句的执行与return的关系，颇为让人迷惑，不知道finally语句是在try的return之前执行还是之后执行？


#### 3.1 finally和return案例1分析
- 首先看一下代码案例。finally语句在return语句执行之后return返回之前执行的。
    ```
    public class FinallyTest1 {
    
        public static void main(String[] args) {
            System.out.println(test1());
        }
    
        public static int test1() {
            int b = 20;
            try {
                System.out.println("try block");
                return b += 80; 
            } catch (Exception e) {
                System.out.println("catch block");
            } finally {
                System.out.println("finally block");
                if (b > 25) {
                    System.out.println("b>25, b = " + b);
                }
            }
            return b;
        }
    }
    ```
- 运行结果是：
    ```
    try block
    finally block
    b>25, b = 100
    100
    ```
- 得出结论：说明return语句已经执行了再去执行finally语句，不过并没有直接返回，而是等finally语句执行完了再返回结果。




#### 3.2 finally和return案例2分析
- 首先看一下代码案例
    ```
    public class FinallyTest1 {
        public static void main(String[] args) {
            System.out.println(test11());
        }
        public static String test11() {
            try {
                System.out.println("try block");
                return test12();
            } finally {
                System.out.println("finally block");
            }
        }
    
        public static String test12() {
           System.out.println("return statement");
           return "after return";
        }
    }
    ```
- 运行结果为：
    ```
    try block
    return statement
    finally block
    after return
    ```
- 得出结论：说明try中的return语句先执行了但并没有立即返回，等到finally执行结束后再返回。


#### 3.3 finally中return和try的return案例1
- 看了上面的案例，大家可能会想：如果finally里也有return语句，那么是不是就直接返回了，try中的return就不能返回了？看下面。finally块中的return语句会覆盖try块中的return返回。
    ```
    public class FinallyTest2 {
        public static void main(String[] args) {
            System.out.println(test2());
        }
    
        public static int test2() {
            int b = 20;
            try {
                System.out.println("try block");
                return b += 80;
            } catch (Exception e) {
                System.out.println("catch block");
            } finally {
                System.out.println("finally block");
                if (b > 25) {
                    System.out.println("b>25, b = " + b);
                }
                return 200;
            }
            // return b;
        }
    }
    ```
- 运行结果是：
    ```
    try block
    finally block
    b>25, b = 100
    200
    ```
- 得出结论
    - 这说明finally里的return直接返回了，就不管try中是否还有返回语句，这里还有个小细节需要注意，finally里加上return过后，finally外面的return b就变成不可到达语句了，也就是永远不能被执行到，**所以需要注释掉否则编译器报错**。


#### 3.4 finally中return和try的return案例2
- 这里大家可能又想：如果finally里没有return语句，但修改了b的值，那么try中return返回的是修改后的值还是原值？看下面。
- 如果finally语句中没有return语句覆盖返回值，那么原来的返回值可能因为finally里的修改而改变也可能不变。[博客](https://github.com/yangchong211/YCBlogs)
    ```
    public class FinallyTest3 {
    
        public static void main(String[] args) {
            System.out.println(test3());
        }
    
        public static int test3() {
            int b = 20;
            try {
                System.out.println("try block");
                return b += 80;
            } catch (Exception e) {
                System.out.println("catch block");
            } finally {
                System.out.println("finally block");
                if (b > 25) {
                    System.out.println("b>25, b = " + b);
                }
                b = 150;
            }
            return 2000;
        }
    }
    ```
- 运行结果是：
    ```
    try block
    finally block
    b>25, b = 100
    100
    ```
- 代码如下所示
    ```
    public class FinallyTest6{
        public static void main(String[] args) {
            System.out.println(getMap().get("KEY").toString());
        }
         
        public static Map<String, String> getMap() {
            Map<String, String> map = new HashMap<String, String>();
            map.put("KEY", "INIT");
            try {
                map.put("KEY", "TRY");
                return map;
            }catch (Exception e) {
                map.put("KEY", "CATCH");
            }finally {
                map.put("KEY", "FINALLY");
                map = null;
            }
            return map;
        }
    }
    ```
- 运行结果是：
    ```
    FINALLY
    ```
- 产生疑问？
    - 为什么测试用例1中finally里的b = 150;并没有起到作用而测试用例2中finally的map.put("KEY", "FINALLY");起了作用而map = null;却没起作用呢？这就是Java到底是传值还是传址的问题了，里面有详细的解答，简单来说就是：Java中只有传值没有传址，这也是为什么map = null这句不起作用。这同时也说明了返回语句是try中的return语句而不是 finally外面的return b;这句，不相信的话可以试下，将return b;改为return 294，对原来的结果没有一点影响。



#### 3.5 try块里的return一定执行吗
- try块里的return语句在异常的情况下不会被执行，这样具体返回哪个看情况。
    ```
    public class FinallyTest4 {
    
        public static void main(String[] args) {
            System.out.println(test4());
        }
    
        public static int test4() {
            int b = 20;
            try {
                System.out.println("try block");
                b = b / 0;
                return b += 80;
            } catch (Exception e) {
                b += 15;
                System.out.println("catch block");
            } finally {
                System.out.println("finally block");
                if (b > 25) {
                    System.out.println("b>25, b = " + b);
                }
                b += 50;
            }
            return b;
        }
    }
    ```
- 运行结果是：
    ```
    try block
    catch block
    finally block
    b>25, b = 35
    85
    ```
- 得出结论：这里因为在return之前发生了除0异常，所以try中的return不会被执行到，而是接着执行捕获异常的catch 语句和最终的finally语句，此时两者对b的修改都影响了最终的返回值，这时return b;就起到作用了。当然如果你这里将return b改为return 300什么的，最后返回的就是300，这毋庸置疑。




### 其他介绍
#### 01.关于博客汇总链接
- 1.[技术博客汇总](https://www.jianshu.com/p/614cb839182c)
- 2.[开源项目汇总](https://blog.csdn.net/m0_37700275/article/details/80863574)
- 3.[生活博客汇总](https://blog.csdn.net/m0_37700275/article/details/79832978)
- 4.[喜马拉雅音频汇总](https://www.jianshu.com/p/f665de16d1eb)
- 5.[其他汇总](https://www.jianshu.com/p/53017c3fc75d)



#### 02.关于我的博客
- 我的个人站点：
- github：https://github.com/yangchong211
- 知乎：https://www.zhihu.com/people/yczbj/activities
- 简书：http://www.jianshu.com/u/b7b2c6ed9284
- csdn：http://my.csdn.net/m0_37700275
- 喜马拉雅听书：http://www.ximalaya.com/zhubo/71989305/
- 开源中国：https://my.oschina.net/zbj1618/blog
- 泡在网上的日子：http://www.jcodecraeer.com/member/content_list.php?channelid=1
- 邮箱：yangchong211@163.com
- 阿里云博客：https://yq.aliyun.com/users/article?spm=5176.100- 239.headeruserinfo.3.dT4bcV
- segmentfault头条：https://segmentfault.com/u/xiangjianyu/articles
- 掘金：https://juejin.im/user/5939433efe88c2006afa0c6e

