#### 目录介绍
- 01.什么是异步支持
    - 1.1 异步线程概念
    - 1.2 Future和Stream
    - 1.3 async和await
    - 1.4 async注意事项
- 02.Future介绍
    - 2.1 Future是什么
    - 2.2 Future.then
    - 2.3 Future.whenComplete
    - 2.4 Future.wait
    - 2.5 Future案例查看
- 03.Async/await介绍
    - 3.1 回调地狱(Callback Hell)
    - 3.2 Future消除Callback Hell
    - 3.3 async/await消除callback hell
- 04.Stream介绍
    - 4.1 和Future区别
    - 4.2 Stream应用场景


### 01.什么是异步支持
#### 1.1 异步线程概念
- 思考一下，为何有异步？
    - Dart是一个单线程语言，可以理解成物理线路中的串联，当其遇到有延迟的运算（比如IO操作、延时执行）时，线程中按顺序执行的运算就会阻塞，用户就会感觉到卡顿，于是通常用异步处理来解决这个问题。也就是说异步主要解决线程阻塞的问题……
- Dart单线程模型
    - Dart 在单线程中是以消息循环机制来运行的，其中包含两个任务队列，一个是“微任务队列”  **microtask queue**，另一个叫做“事件队列” **event queue**。微任务队列的执行优先级高于事件队列。
- Dart线程运行过程
    - 来介绍一下Dart线程运行过程，入口函数 main() 执行完后，消息循环机制便启动了。
    - 首先会按照先进先出的顺序逐个执行微任务队列中的任务，当所有微任务队列执行完后便开始执行事件队列中的任务，事件任务执行完毕后再去执行微任务，如此循环往复，生生不息。
- 部事件任务都在事件队列中
    - 在Dart中，所有的外部事件任务都在事件队列中，如IO、计时器、点击、以及绘制事件等，而微任务通常来源于Dart内部，并且微任务非常少。
    - 之所以如此，是因为微任务队列优先级高，如果微任务太多，执行时间总和就越久，事件队列任务的延迟也就越久，对于GUI应用来说最直观的表现就是比较卡，所以必须得保证微任务队列不会太长。值得注意的是，我们可以通过`Future.microtask(…)`方法向微任务队列插入一个任务。
- 一个任务异常会影响其他任务吗
    - 在事件循环中，当某个任务发生异常并没有被捕获时，程序并不会退出，而直接导致的结果是**当前任务**的后续代码就不会被执行了，也就是说一个任务中的异常是不会影响其它任务执行的。



#### 1.2 Future和Stream
- Dart类库有非常多的返回`Future`或者`Stream`对象的函数。
    - 这些函数被称为**异步函数**：它们只会在设置好一些耗时操作之后返回，比如像 IO操作。而不是等到这个操作完成。
- `async`和`await`关键词支持了异步编程，允许您写出和同步代码很像的异步代码。



#### 1.3 async和await
- async await 这两个关键字是dart语言的特性，能让你写出看起来像是“同步”的“异步”代码。
- 先看一个方法案例：
    ```
      /*返回值为Future<String>类型，即其返回值未来是一个String类型的值*/
      /*async关键字声明该函数内部有代码需要延迟执行*/
      getData() async {    
        /*await关键字声明运算为延迟执行，然后return运算结果*/
        return await "This is a doubi"; 
      }
    ```
- 然后我们尝试调用这个方法，并获取返回值。然后控制台报错了….
    ```
    String data = getData();
    ```
- 为何为报错，原因是什么呢
    - 因为data是String类型，而函数getData()是一个异步操作函数，其返回值是一个await延迟执行的结果。在Dart中，有await标记的运算，其结果值都是一个Future对象，Future不是String类型，所以就报错了。
- 如果调用一个异步函数，并没有返回值，又该如何处理
    - 比如你执行一个异步初始化，无返回值。不建议直接调用，虽然不会报错，但可能出现代码业务问题。建议使用第一种方式，这是为什么呢？
    - todo，思考下
    ```
    ///初始化
    @override
    Future<void> fetchApolloData() async {
        ApolloModel fetchApolloData =
            await ApolloService.fetchApolloData(TOGGLE_MAP_STYLE);
        //省略部分代码
    }
    
    void test(){
        //第一种方式：初始化
        Future(() async {
          MapResourceService _mapResourceService = mapResourceService();
          await fetchApolloData();
        });
        //第二种方式：不要像下面这样调用
        //fetchApolloData();
    }
    ```
- 总结一下：
    - 在获取异步方法中直接 return await .. .的时候，实际上返回的是一个延迟计算的Future对象。
- 还有两点需要注意：
    - await关键字必须在async函数内部使用
    - 调用async函数必须使用await关键字



#### 1.4 async注意事项
- 一个 async 方法 是函数体被标记为 async 的方法。 虽然异步方法的执行可能需要一定时间，但是 异步方法立刻返回 - 在方法体还没执行之前就返回了。
    ```
    void getHttp async {
        // TODO ---
    }
    ```
    - 在一个方法上添加 async 关键字，则这个方法返回值为 Future。 
        - 例如，下面是一个返回字符串的同步方法：
        ```
        String loadAppVersion() => "1.0.2"
        ```
    - 使用 async 关键字，则该方法返回一个 Future，并且 认为该函数是一个耗时的操作。
        ```
        Futre<String> loadAppVersion() async  => "1.0.2"
        ```
    - 注意，方法的函数体并不需要使用 Future API。 Dart 会自动在需要的时候创建 Future 对象。
- 好的代码是这样的
    ```
    void main() {
     //调用异步方法
     doAsync();
    }
    
    // 在函数上声明了 async 表明这是一个异步方法
    Future<bool> doAsync() async {
      try {
        // 这里是一个模拟请求一个网络耗时操作
        var result = await getHttp();
        //请求出来的结果
        return printResult(result);
      } catch (e) {
        print(e);
        return false;
      }
    }
    //将请求出来的结果打印出来
    Future<bool> printResult(summary) {
      print(summary);
    }
    
    //开始模拟网络请求 等待 5 秒返回一个字符串
    getHttp() {
     return new Future.delayed(Duration(seconds: 5), () => "Request Succeeded");
    }
    ```
- 不好的写法
    ```
    void main() {
     doAsync();
    }
    
    Future<String> doAsync() async {
        return  getHttp().then((r){
          return printResult(r);
        }).catchError((e){
          print(e);
        });
    }
    
    Future<String> printResult(summary) {
      print(summary);
    }
    
    Future<String> getHttp() {
     return new Future.delayed(Duration(seconds: 5), () => "Request Succeeded");
    }
    ```



### 02.Future介绍
#### 2.1 Future是什么
- `Future`是什么
    - 与JavaScript中的`Promise`非常相似，表示一个异步操作的最终完成（或失败）及其结果值的表示。
    - 简单来说，它就是用于处理异步操作的，异步处理成功了就执行成功的操作，异步处理失败了就捕获错误或者停止后续操作。
    - 一个Future只会对应一个结果，要么成功，要么失败。
- 通俗解释Future
    - Future表示一件“将来”会发生的事情，将来可以从Future中取到一个值。当一个方法返回一个Future的事情，发生两件事情：
        - 这个方法将某件事情排队，返回一个未完成的Future。
        - 当这件事情完毕之后，Future的状态会变成已完成，这个时候就可以取到这件事情的返回值了。
- Future返回值
    - 请记住，`Future` 的所有API的返回值仍然是一个`Future`对象，所以可以很方便的进行链式调用。
- 如何获取Future返回值，有两种方式：
    - 使用async配合await
    - 使用Future提供的api，这种方式其实就是用Future的then方法获取返回值。


#### 2.2 Future.then
- 为了方便示例，在本例中我们使用`Future.delayed` 
    - 创建了一个延时任务（实际场景会是一个真正的耗时任务，比如一次网络请求），即2秒后返回结果字符串"hi world!"，然后我们在`then`中接收异步结果并打印结果，代码如下：
    ```dart
    Future.delayed(new Duration(seconds: 2),(){
       return "hi world!";
    }).then((data){
       print(data);
    });
    ```

#### 2.3 Future.catchError
- 如果异步任务发生错误，我们可以在`catchError`中捕获错误，我们将上面示例改为：
    ```dart
    Future.delayed(new Duration(seconds: 2),(){
       //return "hi world!";
       throw AssertionError("Error");  
    }).then((data){
       //执行成功会走到这里  
       print("success");
    }).catchError((e){
       //执行失败会走到这里  
       print(e);
    });
    ```
- 在本示例中，我们在异步任务中抛出了一个异常
    - `then `的回调函数将不会被执行，取而代之的是 `catchError`回调函数将被调用；
    - 但是，并不是只有 `catchError`回调才能捕获错误，`then`方法还有一个可选参数`onError`，我们也可以它来捕获异常：
    ```dart
    Future.delayed(new Duration(seconds: 2), () {
    	//return "hi world!";
    	throw AssertionError("Error");
    }).then((data) {
    	print("success");
    }, onError: (e) {
    	print(e);
    });
    ```


#### 2.3 Future.whenComplete
- 有些时候，我们会遇到无论异步任务执行成功或失败都需要做一些事的场景
    - 比如在网络请求前弹出加载对话框，在请求结束后关闭对话框。
    - 这种场景，有两种方法，第一种是分别在`then`或`catch`中关闭一下对话框，第二种就是使用`Future`的`whenComplete`回调：
    ```dart
    Future.delayed(new Duration(seconds: 2),(){
       //return "hi world!";
       throw AssertionError("Error");
    }).then((data){
       //执行成功会走到这里 
       print(data);
    }).catchError((e){
       //执行失败会走到这里   
       print(e);
    }).whenComplete((){
       //无论成功或失败都会走到这里
    });
    ```



#### 2.4 Future.wait
- 先说一下场景
    - 有些时候，我们需要等待多个异步任务都执行结束后才进行一些操作，比如我们有一个界面，需要先分别从两个网络接口获取数据，获取成功后，我们需要将两个接口数据进行特定的处理后再显示到UI界面上，应该怎么做？
- 答案是`Future.wait`
    - 它接受一个`Future`数组参数，只有数组中所有`Future`都执行成功后，才会触发`then`的成功回调，只要有一个`Future`执行失败，就会触发错误回调。
    - 下面通过模拟`Future.delayed` 来模拟两个数据获取的异步任务，等两个异步任务都执行成功时，将两个异步任务的结果拼接打印出来，代码如下：
    ```dart
    Future.wait([
      // 2秒后返回结果  
      Future.delayed(new Duration(seconds: 2), () {
        return "hello";
      }),
      // 4秒后返回结果  
      Future.delayed(new Duration(seconds: 4), () {
        return " world";
      })
    ]).then((results){
      print(results[0]+results[1]);
    }).catchError((e){
      print(e);
    });
    ```
- 执行上面代码，4秒后你会在控制台中看到“hello world”。


#### 2.5 Future案例查看
- 先来看一个案例
    ```
      void doAsyncs() async{
        //then catchError whenComplete
        new Future(() => futureTask()) //  异步任务的函数
            .then((m) => "1-:$m") //   任务执行完后的子任务
            .then((m) => print('2-$m')) //  其中m为上个任务执行完后的返回的结果
            .then((_) => new Future.error('3-:error'))
            .then((m) => print('4-'))
            .whenComplete(() => print('5-')) //不是最后执行whenComplete，通常放到最后回调
            .catchError((e) => print('6-catchError:' + e), test: (Object o) {
          print('7-:' + o);
          return true; //返回true，会被catchError捕获
        })
            .then((_) => new Future.error('11-:error'))
            .then((m) => print('10-'))
            .catchError((e) => print('8-:' + e))
        ;
      }
    
      futureTask() {
        return Future.delayed(Duration(seconds: 5),()  => "9-走去跑步");
      }
    ```
- 执行结果
    ```
    2019-06-21 18:34:21.937 16501-16583/com.hwmc.auth I/flutter: 2-1-:9-走去跑步
    2019-06-21 18:34:21.945 16501-16583/com.hwmc.auth I/flutter: 5-
    2019-06-21 18:34:21.948 16501-16583/com.hwmc.auth I/flutter: 7-:3-:error
    2019-06-21 18:34:21.952 16501-16583/com.hwmc.auth I/flutter: 6-catchError:3-:error
    2019-06-21 18:34:21.954 16501-16583/com.hwmc.auth I/flutter: 8-:11-:error
    ```
- 分析结果
    - 当异步函数 futureTask() 执行完会在内存中保存 ‘9-走去跑步’ 然后继续执行下一步 这个时候遇见了 then 现在会在内存中保存 “1-: 9-走去跑步 ”  继续执行 这个时候遇见了打印输出  2-1-:9-走去跑步 。现在第一个打印出来了。接着执行下一个 then() 这个时候遇见了一个 error 异常，Dart 会把这个异常保存在内存直到遇见捕获异常的地方。下面执行 whenComplete 这个函数 打印 5- 。然后遇见了一个捕获异常的函数 catchError 如果 test 返回 true ，会被 catchError 捕获 打印 7-:3-:error  6-catchError:3-:error。如果返回 false 只打印  7-:3-:error，会把 error 抛给下一个 catchError 。继续执行 又遇见了一个 error 11-:error ,现在出现 error 了  所以 then 10- 就不会执行了  。最后就直接捕获异常 打印 "8-11-error"。






### 03.Async/await介绍
- Dart中的`async/await` 
    - 和JavaScript中的`async/await`功能和用法是一模一样的。




#### 3.1 回调地狱(Callback Hell)
- 如果代码中有大量异步逻辑，并且出现大量异步任务依赖其它异步任务的结果时，必然会出现`Future.then`回调中套回调情况。
- 举个例子
    - 比如现在有个需求场景是用户先登录，登录成功后会获得用户ID，然后通过用户ID，再去请求用户个人信息，获取到用户个人信息后，为了使用方便，我们需要将其缓存在本地文件系统，代码如下：
    ``` dart
    //先分别定义各个异步任务
    Future<String> login(String userName, String pwd){
    	...
        //用户登录
    };
    Future<String> getUserInfo(String id){
    	...
        //获取用户信息 
    };
    Future saveUserInfo(String userInfo){
    	...
    	// 保存用户信息 
    }; 
    ```
- 接下来，执行整个任务流：
    ``` dart
    login("alice","******").then((id){
     //登录成功后通过，id获取用户信息    
     getUserInfo(id).then((userInfo){
        //获取用户信息后保存 
        saveUserInfo(userInfo).then((){
           //保存用户信息，接下来执行其它操作
            ...
        });
      });
    })
    ```
- 可以感受一下，如果业务逻辑中有大量异步依赖的情况，将会出现上面这种在回调里面套回调的情况，过多的嵌套会导致的代码可读性下降以及出错率提高，并且非常难维护，这个问题被形象的称为**回调地狱（Callback Hell）**。
- 回调地狱问题在之前JavaScript中非常突出，也是JavaScript被吐槽最多的点，但随着ECMAScript6和ECMAScript7标准发布后，这个问题得到了非常好的解决，而解决回调地狱的两大神器正是ECMAScript6引入了`Promise`，以及ECMAScript7中引入的`async/await`。 而在Dart中几乎是完全平移了JavaScript中的这两者：`Future`相当于`Promise`，而`async/await`连名字都没改。接下来我们看看通过`Future`和`async/await`如何消除上面示例中的嵌套问题。


#### 3.2 Future消除Callback Hell
- 代码如下
    ``` dart
    login("alice","******").then((id){
      	return getUserInfo(id);
    }).then((userInfo){
        return saveUserInfo(userInfo);
    }).then((e){
       //执行接下来的操作 
    }).catchError((e){
      //错误处理  
      print(e);
    });
    ```
- 正如上文所述， *“`Future` 的所有API的返回值仍然是一个`Future`对象，
    - 所以可以很方便的进行链式调用”* ，如果在then中返回的是一个`Future`的话，该`future`会执行，执行结束后会触发后面的`then`回调，这样依次向下，就避免了层层嵌套。




#### 3.3 async/await消除callback hell
- 通过`Future`回调中再返回`Future`的方式虽然能避免层层嵌套，但是还是有一层回调，有没有一种方式能够让我们可以像写同步代码那样来执行异步任务而不使用回调的方式？答案是肯定的，这就要使用`async/await`了，下面我们先直接看代码，然后再解释，代码如下：
    ```dart
    task() async {
       try{
        String id = await login("alice","******");
        String userInfo = await getUserInfo(id);
        await saveUserInfo(userInfo);
        //执行接下来的操作   
       } catch(e){
        //错误处理   
        print(e);   
       }  
    }
    ```
- `async`用来表示函数是异步的
    - 定义的函数会返回一个`Future`对象，可以使用then方法添加回调函数。
- `await` 后面是一个`Future`
    - 表示等待该异步任务完成，异步完成后才会往下走；`await`必须出现在 `async` 函数内部。
- 通过`async/await`将一个异步流用同步的代码表示出来了。
    - 其实，无论是在JavaScript还是Dart中，`async/await`都只是一个语法糖，编译器或解释器最终都会将其转化为一个Promise（Future）的调用链。







### 04.Stream介绍
#### 4.1 和Future区别
- `Stream` 也是用于接收异步事件数据，和`Future` 不同的是，它可以接收多个异步操作的结果（成功或失败）。 
- 也就是说，在执行异步任务时，可以通过多次触发成功或失败事件来传递结果数据或错误异常。


#### 4.2 Stream应用场景
- `Stream`常用于会多次读取数据的异步任务场景，如网络内容下载、文件读写等。举个例子：
    ``` dart
    Stream.fromFutures([
      // 1秒后返回结果
      Future.delayed(new Duration(seconds: 1), () {
        return "hello 1";
      }),
      // 抛出一个异常
      Future.delayed(new Duration(seconds: 2),(){
        throw AssertionError("Error");
      }),
      // 3秒后返回结果
      Future.delayed(new Duration(seconds: 3), () {
        return "hello 3";
      })
    ]).listen((data){
       print(data);
    }, onError: (e){
       print(e.message);
    },onDone: (){
       print("完成");
    });
    ```
- 上面的代码依次会输出：
    ```
    I/flutter (17666): hello 1
    I/flutter (17666): Error
    I/flutter (17666): hello 3
    ```
> 思考题：既然Stream可以接收多次事件，那能不能用Stream来实现一个订阅者模式的事件总线？
































